version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "9885:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.yaml
    volumes:
      - ./:/docs
